### PR TITLE
Fix msvc build

### PR DESCRIPTION
**Pull request by Rodousse**
Fix windows build to try this masterpiece.
It's obvious you don't give a sh*t about windows users, and I agree ! But still here are some fixes to build using MSVC.

# Feature List:
- Rename uint to unsigned int
- Add missing include
- Use a new define from the cmake to be able to use M_PI with MSVC

Fixed using msvc 14.24.28314

Chouchouuuuu

### CODE REVIEW

**Comment by elcerdo** [comment]
kikou @Rodousse and thx for the contribution!
i did not know you where lurking in the shadows :P
this indeed indeed fix build problem on pesky inferior os.

**Comment by elcerdo** [comment]
there is known issues tho.
namely the ball is not displayed and an glopen assert fail in debug.
those should be fixed soon but in the mean time could you confirm you experience those problem too?

**Comment by elcerdo** [comment]
ps i sent you an invitation to give write access to the main repo.
this avoid having the deal with annoying github fork rights.

**Comment by Rodousse** [comment]
Coucou


Ok I got the assert that fails, but since I can't compile the tests without the modifications, so I can't figure out if it comes from those changes, do the tests pass at this [commit](https://github.com/elcerdo/thrust2020/commit/9d654cad488b8164689a5ffaffe87229fcfc52aa) ?
If yes, I'll try to figure out what's going wrong.

And I don't know what "the ball" is... If you're mentionning the circle uround the thruster yep, it's completly screwed !

Thanks for the access ! I won't disappoint you Pierre sama !

**Comment by Rodousse** [comment]
There's an assert failing in test_extract_polygon.cpp line 49...
Failing to load the resource ":map.svg" since it does not exist in the qrc.
But no assert coming from glopen after testing all the widgets 

And I think the ball is correct here, I had no problem with it if it is the big white ball with black strips looking like mentol arnold from adventure time....

**Comment by elcerdo** [comment]
yep that is what the ball should look like.
i pushed a number of fixes on master + enable proper testing on master.
i am merging this right now as this do what is claim to.
we can always open a new pr if shit keep hitting the fan!

**Pull request merged**
